name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - uses: pnpm/action-setup@v3
        with:
          run_install: true
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: 'distribution'
          path: 'dist'
  build_firefox:
    name: Build Firefox extension
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: 'distribution'
          path: 'dist'
      - uses: pnpm/action-setup@v3
      - run: pnpm i web-ext -g
      - run: pip install jsonpatch
      - run: jsonpatch -i dist/manifest.json ci/browser_specific_settings.patch.json
      - run: web-ext sign --use-submission-api --channel listed -s dist -a .
        env:
          WEB_EXT_API_KEY: ${{ secrets.FIREFOX_API_ISSUER }}
          WEB_EXT_API_SECRET: ${{ secrets.FIREFOX_API_SECRET }}
      - run: cp *.xpi extension.xpi
      - uses: actions/upload-artifact@v4
        with:
          name: 'firefox'
          path: 'extension.xpi'
      - uses: yayuyokitano/firefox-addon@v0.0.3-alpha
        with:
          api_key: ${{ secrets.FIREFOX_API_ISSUER }}
          api_secret: ${{ secrets.FIREFOX_API_SECRET }}
          guid: firefox-eu-fixer@schlau.bi
          xpi_path: 'extension.xpi'
  build_chrome:
    name: Build Chrome extension
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: 'distribution'
          path: 'dist'
      - uses: pnpm/action-setup@v3
      - run: pnpm i web-ext -g
      - run: web-ext build -s dist -n eu_fixer_chrome.zip -a .
      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'upload'  # one of: upload, publish, testers
          client_id: ${{ secrets.CHROME_CLIENT }}
          client_secret: ${{ secrets.CHROME_SECRET }}
          refresh_token: ${{ secrets.CHROME_TOKEN }}
          extension_id: 'ibkbklcafplkbehibmbhgndpofkpbfae'
          zip_file: 'eu_fixer_chrome.zip'